---
title: Debugging UNIX sockets with socat
date: 2012-03-19 10:02:01 +1000
updated: 2012-03-23 13:41:01 +1000
disqus identifier: /2012/03/19/debugging-application-interactions-with-socat.html
tags:
- socat
- networking
- unix-sockets
